#!/bin/sh
printf "%s\n" "Checking dependencies... "
for name in \
awk \
curl \
cut \
head \
sed \
tail \
tr \
wc \
xml \
nmap \
xxd \
sudo \
pulseaudio-dlna \
wget \
nohup \
pgrep \
telnet

do
  [ -n "$(command -v  "${name}" 2>/dev/null)" ] || { printf "%s\n" "${name} needs to be installed. See denpencies.json for further information.";deps=1; }
done

if [ -z "${deps}" ] || [ "${deps}" -ne 1 ]; then
  printf "%s\n" "OK... All dependencies are fulfilled."
else
#  printf "%s\n" "$(<dependencies.json)"
  exit 66
fi
